registration/urls.py
from django.urls import path, include

from . import views

app_name = 'registration'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    # Страница регистрации
    path('registration/', views.register, name='register')]

support_service/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('users.urls')),
    path('registration/', include('registration.urls')),

    path('admin/', admin.site.urls)]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    # Домашняя страница
    path('', views.index, name='index'),
    # Вход в систему
    path('accounts/profile/', views.index, name='loggedin'),
    # Выход из системы
    path('registration/log_out', views.log_out, name='log_out'),
    # Страница добавления тикета
    path('new_ticket/', views.new_ticket, name='new_ticket'),
    # Страница успешной отправки тикета
    path('new_ticket/gratitude_words.html', views.gratitude_words, name='gratitude_words'),
    # Просмотр отправленных вопросов
    path('messages/', views.messages, name='messages'),
    path('messages/<int:message_id>/', views.messages, name='message_delete'),
    # Удаление отправленного тикета
    path('record_delete/<int:message_id>/', views.record_delete, name='record_delete'),
    # Переадресация
    path('record_delete/<int:message_id>/messages.html', views.messages),
    # Просмотр ответов саппорта
    path('accounts/profile/users/staff_page.html', views.answer, name='answers'),
    # Просмотр отправленных тикетов (на стороне саппорта)
    path('users/questions.html/', views.questions, name='questions'),
    # Изменение статуса тикета (на стороне саппорта)
    path('users/questions.html/<int:ticket_id>', views.questions, name='questions_status'),
    # Страница для отправки ответа (на стороне саппорта)
    path('feedback/questions.html', views.questions),
    # Переадресация, если ответ успешно отправлен (на стороне саппорта)
    path('feedback/<int:ticket_id>', views.feedback, name='feedback')]

users/models.py
from django.contrib.auth.models import User
from django.db import models


class Ticket(models.Model):
    """
    Сообщение, которое отправляет пользователь для саппорта.
    Имеет 4 параметра:
        1. Само сообщение;
        2. Дата добавления;
        3. Пользователь, который отправил тикет;
        4. Статус тикета.
    """
    message = models.TextField()
    added_date = models.DateTimeField(auto_now_add=True)
    user_data = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.CharField(max_length=8, default='unsolved')

    def __str__(self):
        return self.message


class Answer(models.Model):
    """
    Ответ, который отправяет саппорт.
    Имеет 3 параметра:
        1. Сам ответ;
        2. Дата добавления;
        3. Вопрос, к которому привязан ответ.
    """
    answer = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    question = models.ForeignKey(Ticket, on_delete=models.CASCADE)

    def __str__(self):
        return self.answer

users/forms.py
from django import forms

from .models import Ticket, Answer


class TicketForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = ['message']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea()}


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['answer']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea()}

users/views.py
from django.contrib.auth import logout
from django.shortcuts import render, redirect
from django.core.exceptions import ObjectDoesNotExist
from django.utils.datastructures import MultiValueDictKeyError

from .forms import TicketForm, AnswerForm
from .models import Ticket, Answer

#TODO Сделать правильную авторизацию персонала.


def index(request):
    """
    Временное решение авторизации персонала - проверка по id
    """
    if request.user.id == 1:
        return render(request, 'users/staff_page.html')

    return render(request, 'users/index.html')


def log_out(request):
    logout(request)
    return render(request, 'users/index.html')


def new_ticket(request):
    """
    Если метод GET, просто рендерит страницу с формой.
    Если метод POST, проверяет валидность данных, сохраняет их и перенаправляет пользователя.
    """
    if request.method != 'POST':
        form = TicketForm()

    else:
        form = TicketForm(data=request.POST)

        if form.is_valid():
            ticket = form.save(commit=False)
            ticket.user_data = request.user
            ticket.save()
            return redirect('gratitude_words.html')

    context = {'form': form}
    return render(request, 'users/ticket.html', context)


def gratitude_words(request):
    return render(request, 'users/gratitude_words.html')


def messages(request, message_id=0):
    """
    Выводит список тикетов, отправленных пользователем.
    """
    message = Ticket.objects.filter(user_data=request.user.id).order_by('-added_date')

    context = {'messages': message}
    return render(request, 'users/messages.html', context)


def record_delete(request, message_id):
    """
    Удаляет тикет по решению пользователя.
    """
    try:
        record = Ticket.objects.get(id=message_id)
        record.delete()
    except ObjectDoesNotExist:
        pass

    return redirect('messages.html')


def answer(request):
    """
    Загружает ответы и тикеты, на которые ответил саппорт.
    """
    answer_instance = Answer.objects
    answers = []

    for ans in answer_instance.order_by('-date_added'):
        if ans.question.user_data == request.user:
            answers.append(ans)

    context = {'answers': answers}
    return render(request, 'users/answers.html', context)


def questions(request, ticket_id=0):
    """
    Если метод POST, меняет статус тикета (решенный, нерешенный, замороженный).
    Выводит тикеты пользователей.
    """
    if request.method == 'POST':
        try:
            choice = request.POST['choice']

            ticket = Ticket.objects.get(id=ticket_id)
            ticket.status = choice
            ticket.save()
        except MultiValueDictKeyError:
            pass

    tickets = Ticket.objects.order_by('-added_date')

    context = {'tickets': tickets}
    return render(request, 'users/questions.html', context)


def feedback(request, ticket_id):
    """
    Если метод GET, рендерит страницу с формой, иначе проверяет валидность данных и записывает в БД.
    """
    tickets = Ticket.objects
    answers = Answer.objects

    ticket = tickets.get(id=ticket_id)
    user_name = ticket.user_data

    prev_ans = []  # Список с ответами, если саппорт ранее обрабатывал тикет.

    if request.method != 'POST':
        form = AnswerForm()

    else:
        form = AnswerForm(data=request.POST)

        if form.is_valid():
            answer_ = form.save(commit=False)
            answer_.question = ticket  # Привязывает ответ к соответствующему тикету.
            answer_.save()
            return redirect('questions.html')

    for reply in answers.order_by('-date_added'):
        if reply.question.id == ticket_id:
            prev_ans.append(reply)

    context = {'form': form,
               'ticket': ticket,
               'user_name': user_name,
               'prev_ans': prev_ans}
    return render(request, 'users/reply.html', context)

users/templates/users/answers.html
{% extends "users/base.html" %}

{% block content %}

{% for answer in answers %}
  <p><b>{{ answer }}</b></p>
  <ul>
    <li>{{ answer.question }}</li>
  </ul>
  <p><a href="{% url 'users:new_ticket' %}">Reply</a></p>
{% empty %}
  <p>You have no messages yet.</p>
{% endfor %}

{% endblock content %}

users/templates/users/base.html
<h2 align="center"><a href="{% url 'users:index' %}">Return to Home Page</a></h2>

{% block content %}{% endblock content %}

users/templates/users/gratitude_words.html
{% extends "users/base.html" %}

{% block content %}

<br><br><br><br><br>
<h2 align="center">Your question has been sent! Thank you!</h2>

{% endblock content %}

users/templates/users/index.html
<h1 align="center">Support service</h1>
<br>
<h3 align="center">Welcome to our Support Service! We are always glad to answer Your questions!</h3>
<br>

{% if user.is_authenticated %}
  <p align="center">Hello, <b>{{ user.username }}</b></p>
  <p align="center"><a href="{% url 'users:new_ticket' %}"><b>Ask a question</b></a> -
    <a href="{% url 'users:messages' %}"><b>Messages</b></a> -
    <a href="{% url 'users:answers' %}"><b>Answers</b></a> -
    <a href="{% url 'users:log_out' %}">Log out</a>

{% else %}
  <p align="center"><a href="{% url 'registration:login' %}"><b>Log in</b></a> to write us a message.</p>
{% endif %}

users/templates/users/messages.html
{% extends "users/base.html" %}

{% block content %}

<p>Your messages:</p>
<ul>
    {% for message in messages %}
      <li>
          <p>{{ message }}</p>
          <p>{{ message.added_time }}</p>
          <p><a href="{% url 'users:record_delete' message.id %}">Delete</a></p>
      </li>
    {% empty %}
      <li>You have no messages yet.</li>
    {% endfor %}
</ul>

{% endblock content %}

users/templates/users/questions.html
{% extends "users/base.html" %}

{% block content %}

{% for ticket in tickets %}

  {% if ticket.status == 'solved' %}
    <p><font color="#006400" size="4"><b>{{ ticket.status|capfirst }}</b></font></p>
  {% elif ticket.status == 'unsolved' %}
    <p><font color="#DC143C" size="4"><b>{{ ticket.status|capfirst }}</b></font></p>
  {% else %}
    <p><font color="#00CED1" size="4"><b>{{ ticket.status|capfirst }}</b></font></p>
  {% endif %}

  <h3>{{ ticket.user_data }}</h3>
  <h4>{{ ticket }}</h4>

  <form action="{% url 'users:questions_status' ticket.id %}" method="post">
    {% csrf_token %}
    <input type="radio" name="choice" value="solved"/>
    <font color="#006400"><label>Solved</label></font>

    <input type="radio" name="choice" value="unsolved" />
    <font color="#DC143C"><label>Unsolved</label></font>

    <input type="radio" name="choice" value="frozen"/>
    <font color="#00CED1"><label>Frozen</label></font>
    <br>
    <br>
    <input type="submit" value="Set"/>
  </form>

  <p>
    <a href="{% url 'users:feedback' ticket.id %}">Answer</a>
  </p>
  <br>
{% empty %}
  <p>No questions has sent.</p>
{% endfor %}

{% endblock content %}

users/templates/users/reply.html
{% extends "users/base.html" %}

{% block content %}

{% if ticket.status == 'solved' %}
    <p><font color="#006400" size="4"><b>{{ ticket.status|capfirst }}</b></font></p>
  {% elif ticket.status == 'unsolved' %}
    <p><font color="#DC143C" size="4"><b>{{ ticket.status|capfirst }}</b></font></p>
  {% else %}
    <p><font color="#00CED1" size="4"><b>{{ ticket.status|capfirst }}</b></font></p>
  {% endif %}

<p>You are replying to <b>{{ user_name }}</b></p>

{% if ticket|length > 50 %}
  <p><b>{{ ticket|slice:":50" }}</b></p>
{% else %}
  <p><b>{{ ticket }}</b></p>
{% endif %}

<form action="{% url 'users:feedback' ticket.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Submit</button>
</form>
<br>

{% if prev_ans %}
  <h3>The previous answers are:</h3>

  {% for answer in prev_ans %}
    <p><b>{{ answer }}</b></p>
  {% endfor %}

{% endif %}

{% endblock content %}

users/templates/users/staff_page.html
<h1 align="center">Welcome back, Support Staff!</h1>
<br>
<p align="center"><a href="{% url 'users:questions' %}">Tickets</a> -
    <a href="{% url 'users:log_out' %}">Log out</a></p>

users/templates/users/ticket.html
{% extends "users/base.html" %}

{% block content %}

<p>Write a question below:</p>
<form action="{% url 'users:new_ticket' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Submit</button>
</form>

{% endblock content %}